table Produits
	lineageTag: 4acffc72-8aa7-4ba7-921b-faa2ac95ca1d

	column ProduitId
		dataType: int64
		formatString: 0
		lineageTag: 3ed32731-0eae-45ac-befa-b2d4d3376571
		summarizeBy: none
		sourceColumn: ProduitId

		annotation SummarizationSetBy = Automatic

	column Produit
		dataType: string
		lineageTag: 90cdff01-f2e6-463d-8bd9-e14aa78d61d0
		summarizeBy: none
		sourceColumn: Produit

		annotation SummarizationSetBy = Automatic

	column Categorie
		dataType: string
		lineageTag: f66e5ebf-54a0-4b6f-8e0b-7cb7f6246b4d
		summarizeBy: none
		sourceColumn: Categorie

		annotation SummarizationSetBy = Automatic

	column PrixUnitaireHT
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: e17be880-6f4a-4e83-a1e8-7a1e45e23cb9
		summarizeBy: none
		sourceColumn: PrixUnitaireHT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"fr-FR"}

	partition Produits = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        Web.Contents("https://raw.githubusercontent.com",
				            [RelativePath = "git-cicd-pbi-formation/donnees-formation/main/" & Environnement & "/produits.csv"]),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Types = Table.TransformColumnTypes(Entetes, {
				        {"ProduitId", Int64.Type}, {"Produit", type text}, {"Categorie", type text},
				        {"PrixUnitaireHT", Currency.Type}}, "en-US")
				in
				    Types

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

