table Ventes
	lineageTag: 4530d223-ab2a-4a0d-9111-aee194003748

	measure 'CA HT' = CALCULATE ( SUM ( Ventes[MontantHT] ), Ventes[Statut] <> "Annulée" )
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 323202a6-b3d4-4137-818b-a47d39778ec5

	measure 'Nb commandes' = CALCULATE ( DISTINCTCOUNT ( Ventes[NumCommande] ), Ventes[Statut] <> "Annulée" )
		formatString: 0
		lineageTag: 3c3e1ec4-7b52-4e5e-89a9-eabc0c883910

	measure 'Panier moyen' = DIVIDE ( [CA HT], [Nb commandes] )
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 3fcc2e08-1ed2-4235-a4d5-a3153e3a8f9b

	measure 'Taux d''annulation' = DIVIDE ( CALCULATE ( DISTINCTCOUNT ( Ventes[NumCommande] ), Ventes[Statut] = "Annulée" ), DISTINCTCOUNT ( Ventes[NumCommande] ) )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: bcce0841-d5f6-4700-831a-71a3477a6c23

	measure 'CA HT SPLY' = ```
			
			CALCULATE ( 
			    SUM ( Ventes[MontantHT] ), 
			    Ventes[Statut] <> "Annulée", 
			    SAMEPERIODLASTYEAR(Calendrier[Date])
			)
			```
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: 59ec5934-fc2c-4e69-a6a7-f91163a4ca93

		annotation PBI_FormatHint = {"currencyCulture":"fr-FR"}

	measure 'EVO CA HT VS LY' =
			
			([CA HT] - [CA HT SPLY]) / [CA HT SPLY]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d851550c-2823-49b2-90fd-2a8a394789be

	column NumCommande
		dataType: string
		lineageTag: dcd0f4a5-b2c1-4016-ad4b-2e8eadb59a82
		summarizeBy: none
		sourceColumn: NumCommande

		annotation SummarizationSetBy = Automatic

	column DateCommande
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: a9acd623-af10-4492-b707-b214cb18f9c6
		summarizeBy: none
		sourceColumn: DateCommande

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ProduitId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a4fa3efc-9cc2-477c-be4f-8022d42143b6
		summarizeBy: none
		sourceColumn: ProduitId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 42f08312-9415-44bd-b1ef-98572608373a
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: string
		lineageTag: aa535c0b-ed29-41e7-9817-960cfaa80148
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column Quantite
		dataType: int64
		formatString: 0
		lineageTag: aed1b500-43c5-46f1-b1ac-220de1667af1
		summarizeBy: sum
		sourceColumn: Quantite

		annotation SummarizationSetBy = Automatic

	column MontantHT
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 6fc78de7-a6c2-4362-ad41-0b87d32fc34c
		summarizeBy: sum
		sourceColumn: MontantHT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"fr-FR"}

	column Statut
		dataType: string
		lineageTag: 5dd204df-f8fc-422e-9925-b429779ff8b3
		summarizeBy: none
		sourceColumn: Statut

		annotation SummarizationSetBy = Automatic

	column Environnement
		dataType: string
		lineageTag: 65d4c506-1690-4f48-b646-fb7566bdea48
		summarizeBy: none
		sourceColumn: Environnement

		annotation SummarizationSetBy = Automatic

	partition Ventes = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        Web.Contents("https://raw.githubusercontent.com",
				            [RelativePath = "git-cicd-pbi-formation/donnees-formation/main/" & Environnement & "/ventes.csv"]),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Types = Table.TransformColumnTypes(Entetes, {
				        {"NumCommande", type text}, {"DateCommande", type date}, {"ProduitId", Int64.Type},
				        {"Region", type text}, {"Canal", type text}, {"Quantite", Int64.Type},
				        {"MontantHT", Currency.Type}, {"Statut", type text}, {"Environnement", type text}}, "en-US")
				in
				    Types

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

